name = "mailpal-email-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "KV"
# namespace "mailpal-kv" — shared with frontend (wrangler.jsonc ở root)
id = "a5b47fc2480a46dc9f1b3aff7972c1d1"